<a href="https://colab.research.google.com/github/manbhavsingh/3DFaceReconstruction-With-Occlusion/blob/main/BTP_Part2_Geometry_PAD_OULU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BTP Part 2: 3D Face Geometry-Based Face Presentation Attack Detection (PAD)
## Complete Research Execution, Robustness, Ablation & Reporting Notebook (OULU Pilot-100)

**Research Question:** *Can geometric information extracted from reconstructed 3D facial surfaces provide discriminative information for face presentation-attack detection?*

This notebook orchestrates the complete research workflow: calling repository modules (`src/face_recon_occlusion/`) and scripts (`scripts/`), performing multi-split robustness evaluation, failure analysis, generating publication-ready figures, and exporting scientific summary files.

---

## SECTION 1 — Environment Setup
Inspect Python environment, mount Google Drive (`/content/drive/MyDrive/`), and clone/pull the code repository.

In [1]:
import os
import sys
import subprocess
from pathlib import Path
from datetime import datetime

try:
    from IPython.display import display, Image
except ImportError:
    display = print

print(f"Python Version   : {sys.version}")
print(f"Current Directory: {Path.cwd()}")
print(f"Timestamp        : {datetime.now().isoformat()}")

Python Version   : 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
Current Directory: /content
Timestamp        : 2026-10-15T16:59:18.813833

In [2]:
# Mount Google Drive (Colab Execution)
try:
    from google.colab import drive
    drive.mount("/content/drive")
    print("✅ Google Drive mounted successfully at /content/drive")
except ImportError:
    print("ℹ️ Running outside Google Colab environment. Assuming local filesystem storage.")

Mounted at /content/drive
✅ Google Drive mounted successfully at /content/drive

In [3]:
from pathlib import Path
import subprocess
import os
import sys

repo_dir = Path("/content/3DFaceReconstruction-With-Occlusion")
repo_url = (
    "https://github.com/manbhavsingh/"
    "3DFaceReconstruction-With-Occlusion.git"
)

if not (repo_dir / ".git").is_dir():
    if repo_dir.exists():
        raise RuntimeError(
            f"{repo_dir} exists but is not a Git repository."
        )
    subprocess.run(
        ["git", "clone", repo_url, str(repo_dir)],
        check=True,
    )
else:
    subprocess.run(
        ["git", "-C", str(repo_dir), "pull", "--ff-only", "origin", "main"],
        check=True,
    )

os.chdir(repo_dir)
sys.path.insert(0, str(repo_dir / "src"))

print("Repository:", repo_dir)
print("Setup successful")

Repository: /content/3DFaceReconstruction-With-Occlusion
Setup successful

In [4]:
%cd /content/3DFaceReconstruction-With-Occlusion

!pip install -e . scikit-learn seaborn matplotlib
!python -m compileall -q src scripts

/content
Obtaining file:///content/3DFaceReconstruction-With-Occlusion
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.2.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: opencv-python>=4.8 in /usr/local/lib/python3.13/dist-packages (from face-recon-occlusion==0.1.0) (5.0.0.93)
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.13/dist-packages (from face-recon-occlusion==0.1.0) (2.11.0+cu130)
Requirement already satisfied: torchvision>=0.15 in /usr/local/lib/python3.13/dist-packages (from face-recon-occlusion==0.1.0) (0.26.0+cu130)
Requirement already satisfied: scikit-image>=0.21 in /usr/local/lib/python3.13/dist-packages (from face-recon-occlusion==0.1.0) (0.25.2)
Collecting trimesh>=4.0 (from face-recon-occlusion==0.1.0)
  Downloading trimesh-5.1.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tqdm>=4.66 in /usr/local/lib/python3.13/dist-packages (from face-recon-occlusion==0.1.0) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.21->face-recon-occlusion==0.1.0) (3.7)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.21->face-recon-occlusion==0.1.0) (2.38.0)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.21->face-recon-occlusion==0.1.0) (2026.9.20)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.21->face-recon-occlusion==0.1.0) (0.6)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (4.0.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (2025.12.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0->face-recon-occlusion==0.1.0) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0->face-recon-occlusion==0.1.0) (13.0.85)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0->face-recon-occlusion==0.1.0) (1.8.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0->face-recon-occlusion==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0->face-recon-occlusion==0.1.0) (3.0.3)
Downloading trimesh-5.1.1-py3-none-any.whl (750 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.4/750.4 kB 17.0 MB/s eta 0:00:00
Building wheels for collected packages: face-recon-occlusion
  Building editable for face-recon-occlusion (pyproject.toml) ... done
  Created wheel for face-recon-occlusion: filename=face_recon_occlusion-0.1.0-0.editable-py3-none-any.whl size=3524 sha256=63d3ab9fb48ef27f7deb36c680a720ac50b476c355ef4446f6c6b32260178d28
  Stored in directory: /tmp/pip-ephem-wheel-cache-4njfdqsz/wheels/fc/2d/af/c92ba41bd6ddb1765843e3d928c93327051c995eee0c9ff62b
Successfully built face-recon-occlusion
Installing collected packages: trimesh, face-recon-occlusion
Successfully installed face-recon-occlusion-0.1.0 trimesh-5.1.1

In [5]:
import sys
sys.path.insert(0, "src")

from face_recon_occlusion.geometry import extract_geometry_features
from face_recon_occlusion.data import (
    create_subject_disjoint_split,
    verify_subject_disjoint,
)
from face_recon_occlusion.models import train_svm
from face_recon_occlusion.evaluation import (
    compute_pad_metrics,
    run_ablation_experiments,
)

print("All core modules imported successfully.")

All core modules imported successfully.

In [ ]:
# Verify Repository Directory Structure
assert (repo_dir / "src").exists(), "Missing src/ directory in repository!"
assert (repo_dir / "scripts").exists(), "Missing scripts/ directory in repository!"
print("✅ Repository layout verified (src/ and scripts/ present).")

## SECTION 2 — Dependency Verification
Verify core scientific dependencies (numpy, pandas, scipy, trimesh, scikit-learn, matplotlib, seaborn, tqdm).

In [6]:
import numpy as np
import pandas as pd
import scipy
import trimesh
import sklearn
import matplotlib
import seaborn
import tqdm

print("Dependencies Verified:")
print(f"  numpy        : {np.__version__}")
print(f"  pandas       : {pd.__version__}")
print(f"  scipy        : {scipy.__version__}")
print(f"  trimesh      : {trimesh.__version__}")
print(f"  scikit-learn : {sklearn.__version__}")
print(f"  matplotlib   : {matplotlib.__version__}")
print(f"  seaborn      : {seaborn.__version__}")
print(f"  tqdm         : {tqdm.__version__}")
print("✅ All required dependencies are available.")

Dependencies Verified:
  numpy        : 2.1.3
  pandas       : 2.2.3
  scipy        : 1.16.3
  trimesh      : 5.1.1
  scikit-learn : 1.6.1
  matplotlib   : 3.10.0
  seaborn      : 0.13.2
  tqdm         : 4.67.3
✅ All required dependencies are available.

## SECTION 3 — Repository / Package Setup
Make `src/` importable in `sys.path` and test importing package modules.

In [7]:
# Add src/ directory to sys.path
src_dir = str(repo_dir / "src")
if src_dir not in sys.path:
    sys.path.insert(0, src_dir)

from face_recon_occlusion.geometry import (
    extract_depth_features,
    extract_gradient_features,
    extract_curvature_features,
    extract_geometry_features
)
from face_recon_occlusion.data import create_subject_disjoint_split, verify_subject_disjoint, summarize_split
from face_recon_occlusion.models import train_svm, build_svm_pipeline
from face_recon_occlusion.evaluation import compute_pad_metrics, run_ablation_experiments, analyze_failures

print("✅ Successfully imported repository modules:")
print("   - face_recon_occlusion.geometry (depth, gradient, curvature, features)")
print("   - face_recon_occlusion.data (splits, metadata summaries)")
print("   - face_recon_occlusion.models (SVM pipeline)")
print("   - face_recon_occlusion.evaluation (PAD metrics, ablation, failure analysis)")

✅ Successfully imported repository modules:
   - face_recon_occlusion.geometry (depth, gradient, curvature, features)
   - face_recon_occlusion.data (splits, metadata summaries)
   - face_recon_occlusion.models (SVM pipeline)
   - face_recon_occlusion.evaluation (PAD metrics, ablation, failure analysis)

## SECTION 4 — Drive / Data Validation
Validate dataset root directory, metadata CSV, and 3D OBJ reconstructions.

In [8]:
drive_root = Path("/content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100")
if not drive_root.exists():
    drive_root = repo_dir / "outputs"

meta_path = drive_root / "oulu_subject_disjoint_pilot_100.csv"
if not meta_path.exists():
    meta_path = drive_root / "oulu_geometry_features.csv"
if not meta_path.exists():
    meta_path = repo_dir / "outputs" / "oulu_geometry_features.csv"

mesh_dir = drive_root / "reconstructions"
if not mesh_dir.exists():
    mesh_dir = repo_dir / "outputs" / "reconstructions"

print(f"Data Root Path  : {drive_root} (Exists: {drive_root.exists()})")
print(f"Metadata / CSV  : {meta_path} (Exists: {meta_path.exists()})")
print(f"Reconstructions : {mesh_dir} (Exists: {mesh_dir.exists()})")

assert drive_root.exists(), f"Data root directory not found: {drive_root}"
assert meta_path.exists(), f"Metadata CSV not found: {meta_path}"

if mesh_dir.exists():
    obj_files = sorted(list(mesh_dir.rglob("*.obj")))
    print(f"Total OBJ Meshes Found: {len(obj_files)}")
else:
    print("ℹ️ Reconstructions folder not present locally; feature extraction CSV will be loaded from cache.")
print("✅ Data validation complete.")

Data Root Path  : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100 (Exists: True)
Metadata / CSV  : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/oulu_subject_disjoint_pilot_100.csv (Exists: True)
Reconstructions : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/reconstructions (Exists: True)
Total OBJ Meshes Found: 100
✅ Data validation complete.

## SECTION 5 — Metadata Inspection
Inspect metadata CSV columns, subject count, and class distribution.

In [9]:
meta_df = pd.read_csv(meta_path)
print(f"Metadata Shape: {meta_df.shape}")
print(f"Metadata Columns: {list(meta_df.columns)}\n")
print("First 5 Rows:")
display(meta_df.head())

print("\nSubject Distribution:")
print(f"  Total Unique Subjects: {meta_df['subject_id'].nunique()}")
print(f"  Subject IDs: {sorted(meta_df['subject_id'].unique())}")

print("\nClass Distribution (0 = Bona Fide, 1 = Spoof):")
print(meta_df["label"].value_counts().sort_index())

for col in ["sample_id", "subject_id", "label"]:
    assert col in meta_df.columns, f"CRITICAL: Missing required column '{col}' in metadata CSV!"

print("\n✅ Metadata fields verified successfully.")

Metadata Shape: (100, 10)
Metadata Columns: ['sample_id', 'image_path', 'device_id', 'session_id', 'subject_id', 'attack_id', 'recording_id', 'label', 'label_name', 'split']

First 5 Rows:

,sample_id,image_path,device_id,session_id,subject_id,attack_id,recording_id,label,label_name,split
0,1_1_51_1_1,/content/drive/MyDrive/Oulu-NPU/true/1_1_51_1_...,1,1,51,1,1,0,bona_fide,test
1,1_1_51_2_1,/content/drive/MyDrive/Oulu-NPU/false/1_1_51_2...,1,1,51,2,1,1,spoof,test
2,1_1_51_3_1,/content/drive/MyDrive/Oulu-NPU/false/1_1_51_3...,1,1,51,3,1,1,spoof,test
3,1_1_51_4_1,/content/drive/MyDrive/Oulu-NPU/false/1_1_51_4...,1,1,51,4,1,1,spoof,test
4,1_1_51_5_1,/content/drive/MyDrive/Oulu-NPU/false/1_1_51_5...,1,1,51,5,1,1,spoof,test

Subject Distribution:
  Total Unique Subjects: 20
  Subject IDs: [np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55)]

Class Distribution (0 = Bona Fide, 1 = Spoof):
label
0    20
1    80
Name: count, dtype: int64

✅ Metadata fields verified successfully.

## SECTION 6 — SINGLE OBJ GEOMETRY TEST
Sanity Check: Extract 6 geometric features from a sample OBJ mesh if present and verify finite non-NaN values.

In [10]:
features_to_check = [
    "depth_std", "depth_range",
    "gradient_mean", "gradient_std",
    "gaussian_curvature_mean", "gaussian_curvature_std"
]

if "obj_files" in locals() and len(obj_files) > 0:
    test_obj_path = obj_files[0]
    print(f"Testing Geometry Extraction on Sample OBJ: {test_obj_path.name}")
    test_feats = extract_geometry_features(test_obj_path)
    print("\n==========================================")
    print("SINGLE OBJ GEOMETRY FEATURE OUTPUT")
    print("==========================================")
    for fname in features_to_check:
        val = test_feats[fname]
        print(f"{fname:25s}: {val:.8f}")
        assert np.isfinite(val) and not np.isnan(val), f"Invalid feature value: {val}"
    print("\n✅ Single OBJ geometry extraction sanity test PASSED.")
else:
    print("ℹ️ Skipping single OBJ test since raw OBJ files are handled via pre-extracted CSV cache.")

Testing Geometry Extraction on Sample OBJ: 1_1_36_1_1.obj

==========================================
SINGLE OBJ GEOMETRY FEATURE OUTPUT
==========================================
depth_std                : 0.11246039
depth_range              : 0.47852442
gradient_mean            : 0.57269453
gradient_std             : 0.62868567
gaussian_curvature_mean  : -0.00329710
gaussian_curvature_std   : 0.04559289

✅ Single OBJ geometry extraction sanity test PASSED.

## SECTION 7 — CACHE-FIRST FEATURE EXTRACTION
Execute batch geometry feature extraction script across dataset.

In [11]:
output_feature_csv = drive_root / "oulu_geometry_features.csv"
if not output_feature_csv.exists():
    output_feature_csv = repo_dir / "outputs" / "oulu_geometry_features.csv"

if mesh_dir.exists() and len(list(mesh_dir.rglob("*.obj"))) > 0:
    script_path = repo_dir / "scripts" / "run_geometry_extraction.py"
    subprocess.run([
        sys.executable, str(script_path),
        "--mesh-dir", str(mesh_dir),
        "--metadata-csv", str(meta_path),
        "--output-csv", str(output_feature_csv)
    ], cwd=str(repo_dir), check=True)
else:
    print(f"ℹ️ Reusing cached feature CSV at: {output_feature_csv}")

assert output_feature_csv.exists(), f"Feature CSV not found: {output_feature_csv}"
print(f"✅ Feature extraction table ready: {output_feature_csv}")

✅ Feature extraction table ready: /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/oulu_geometry_features.csv

## SECTION 8 — FEATURE CSV VALIDATION & METADATA MERGE
Load extracted feature table, normalize sample IDs, backfill metadata if needed, and verify data integrity.

In [12]:
feats_df = pd.read_csv(output_feature_csv)
print(f"Loaded Feature Table Shape: {feats_df.shape}")
print(f"Initial Columns: {list(feats_df.columns)}\n")

def norm_id(sid):
    if pd.isna(sid): return ""
    s = str(sid).strip()
    for ext in [".jpg", ".jpeg", ".png", ".obj", ".mat"]:
        if s.lower().endswith(ext):
            s = s[:-len(ext)]
    return s

if "subject_id" not in feats_df.columns or "label" not in feats_df.columns:
    print("ℹ️ Backfilling missing metadata ('subject_id', 'label') into feature table...")
    feats_df["_norm_id"] = feats_df["sample_id"].apply(norm_id)
    meta_df["_norm_id"] = meta_df["sample_id"].apply(norm_id)
    cols_to_add = [c for c in ["subject_id", "label", "attack_id", "device_id"] if c in meta_df.columns and c not in feats_df.columns]
    feats_df = feats_df.merge(meta_df[["_norm_id"] + cols_to_add], on="_norm_id", how="left").drop(columns=["_norm_id"])
    feats_df.to_csv(output_feature_csv, index=False)
    print(f"✅ Updated feature table saved to {output_feature_csv}")

for fname in features_to_check:
    assert fname in feats_df.columns, f"Missing feature column: {fname}"
    assert feats_df[fname].isna().sum() == 0, f"NaNs found in {fname}"

print("Summary Statistics of Extracted Baseline 6 Features:")
display(feats_df[features_to_check].describe())
print("\n✅ Feature CSV validation and metadata backfill PASSED.")

Loaded Feature Table Shape: (100, 18)
Initial Columns: ['sample_id', 'subject_id', 'label', 'attack_id', 'device_id', 'depth_std', 'depth_range', 'gradient_mean', 'gradient_std', 'gaussian_curvature_mean', 'gaussian_curvature_std', 'xy_scale', 'curvature_radius', 'image_path', 'session_id', 'recording_id', 'label_name', 'split']

Summary Statistics of Extracted Baseline 6 Features:

,depth_std,depth_range,gradient_mean,gradient_std,gaussian_curvature_mean,gaussian_curvature_std
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.104543,0.489885,0.554455,0.568035,-0.004244,0.051098
std,0.003939,0.021165,0.026253,0.060072,0.000861,0.003173
min,0.097348,0.442308,0.503340,0.463076,-0.006496,0.045427
25%,0.101640,0.474357,0.535434,0.528996,-0.004632,0.048649
50%,0.104058,0.488180,0.549031,0.567184,-0.004228,0.050960
75%,0.107907,0.503779,0.569831,0.601611,-0.003608,0.053574
max,0.112803,0.538031,0.637462,0.712188,-0.002749,0.058837

✅ Feature CSV validation and metadata backfill PASSED.

## SECTION 9 — PRIMARY SUBJECT-DISJOINT SPLIT VALIDATION (Seed 42)
Verify zero subject identity leakage between primary training and testing splits.

In [13]:
feats_df1 = create_subject_disjoint_split(feats_df.copy(), subject_col="subject_id", label_col="label", test_ratio=0.25, random_state=42)

train_subset1 = feats_df1[feats_df1["split"] == "train"]
test_subset1 = feats_df1[feats_df1["split"] == "test"]

verify_subject_disjoint(train_subset1, test_subset1, subject_col="subject_id")

split_summary1 = summarize_split(feats_df1, subject_col="subject_id", label_col="label")
print("==========================================")
print("PRIMARY SUBJECT-DISJOINT SPLIT (SEED 42)")
print("==========================================")
print(f"Train Samples  : {split_summary1['n_train_samples']} (Subjects: {split_summary1['n_train_subjects']})")
print(f"Test Samples   : {split_summary1['n_test_samples']} (Subjects: {split_summary1['n_test_subjects']})")
print(f"Train Subjects : {sorted(list(train_subset1['subject_id'].unique()))}")
print(f"Test Subjects  : {sorted(list(test_subset1['subject_id'].unique()))}")
print(f"Train Classes  : {split_summary1['train_class_dist']}")
print(f"Test Classes   : {split_summary1['test_class_dist']}")

overlap1 = set(train_subset1["subject_id"]).intersection(set(test_subset1["subject_id"]))
print(f"Subject Overlap: {overlap1} (Count: {len(overlap1)})")
print("\n✅ Primary subject-disjoint split verified: ZERO subject identity leakage.")

==========================================
PRIMARY SUBJECT-DISJOINT SPLIT (SEED 42)
==========================================
Train Samples  : 75 (Subjects: 15)
Test Samples   : 25 (Subjects: 5)
Train Subjects : [np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(52), np.int64(54), np.int64(55)]
Test Subjects  : [np.int64(36), np.int64(37), np.int64(44), np.int64(51), np.int64(53)]
Train Classes  : {1: 60, 0: 15}
Test Classes   : {1: 20, 0: 5}
Subject Overlap: set() (Count: 0)

✅ Primary subject-disjoint split verified: ZERO subject identity leakage.

## SECTION 10 — BASELINE SVM EVALUATION (Seed 42)
Train `StandardScaler` + `SVC(kernel="rbf", C=1.0, gamma="scale", class_weight="balanced", random_state=42)` fitted strictly on primary training split.

In [14]:
X_train_full1 = train_subset1[features_to_check].values
y_train_full1 = train_subset1["label"].values
X_test_full1 = test_subset1[features_to_check].values
y_test_full1 = test_subset1["label"].values

svm_model1 = train_svm(X_train_full1, y_train_full1, C=1.0, kernel="rbf", class_weight="balanced", random_state=42)
print("✅ Baseline RBF SVM pipeline fitted strictly on Primary X_train.")

y_pred_baseline1 = svm_model1.predict(X_test_full1)
y_prob_baseline1 = svm_model1.predict_proba(X_test_full1)[:, 1]

✅ Baseline RBF SVM pipeline fitted strictly on Primary X_train.

## SECTION 11 — PRIMARY PAD METRICS COMPUTATION
Compute ISO/IEC 30107-3 metrics (APCER, BPCER, ACER, ROC-AUC, Accuracy, Precision, Recall, F1, Confusion Matrix).

In [15]:
base_metrics1 = compute_pad_metrics(y_test_full1, y_pred_baseline1, y_prob_baseline1)

print("==========================================")
print("PRIMARY 6-FEATURE SVM EVALUATION RESULTS")
print("==========================================")
print(f"Accuracy   : {base_metrics1['accuracy']:.4f}")
print(f"APCER      : {base_metrics1['apcer']:.4f} (Spoof False Acceptance Rate)")
print(f"BPCER      : {base_metrics1['bpcer']:.4f} (Bona Fide False Rejection Rate)")
print(f"ACER       : {base_metrics1['acer']:.4f} (Average Classification Error Rate)")
print(f"ROC-AUC    : {base_metrics1['roc_auc']:.4f}")
print(f"Precision  : {base_metrics1['precision']:.4f}")
print(f"Recall     : {base_metrics1['recall']:.4f}")
print(f"F1-Score   : {base_metrics1['f1']:.4f}")
print(f"\nConfusion Matrix (TN, FP, FN, TP):")
print(f"  TN={base_metrics1['tn']}, FP={base_metrics1['fp']}, FN={base_metrics1['fn']}, TP={base_metrics1['tp']}")

==========================================
PRIMARY 6-FEATURE SVM EVALUATION RESULTS
==========================================
Accuracy   : 0.7200
APCER      : 0.3000 (Spoof False Acceptance Rate)
BPCER      : 0.2000 (Bona Fide False Rejection Rate)
ACER       : 0.2500 (Average Classification Error Rate)
ROC-AUC    : 0.3000
Precision  : 0.9333
Recall     : 0.7000
F1-Score   : 0.8000

Confusion Matrix (TN, FP, FN, TP):
  TN=4, FP=1, FN=6, TP=14

## SECTION 12 — FIVE ABLATION EXPERIMENTS & RESULTS TABLE DISPLAY
Execute all 5 required ablation feature combinations using `scripts/run_ablation_experiments.py` and display the ACTUAL `ablation_results/results.csv` output table.

In [16]:
ablation_out_dir = drive_root / "ablation_results"
if not ablation_out_dir.exists():
    ablation_out_dir = repo_dir / "outputs" / "ablation_results"

ablation_script = repo_dir / "scripts" / "run_ablation_experiments.py"
subprocess.run([
    sys.executable, str(ablation_script),
    "--features-csv", str(output_feature_csv),
    "--metadata-csv", str(meta_path),
    "--output-dir", str(ablation_out_dir),
    "--seed", "42"
], cwd=str(repo_dir), check=True)

ablation_results_file = ablation_out_dir / "results.csv"
assert ablation_results_file.exists(), f"Ablation results file not found at {ablation_results_file}"

ablation_results_df = pd.read_csv(ablation_results_file)
print("\n==========================================================================================")
print("ACTUAL CONTENTS OF ablation_results/results.csv")
print("==========================================================================================")
display(ablation_results_df[["experiment", "num_features", "accuracy", "apcer", "bpcer", "acer", "roc_auc", "precision", "recall", "f1", "feature_list"]])
print(f"\n✅ Loaded and displayed actual 5 ablation results from: {ablation_results_file}")

==========================================================================================
ACTUAL CONTENTS OF ablation_results/results.csv
==========================================================================================

,experiment,num_features,accuracy,apcer,bpcer,acer,roc_auc,precision,recall,f1,feature_list
0,Exp_1_Depth_Only,2,0.56,0.45,0.4,0.425,0.57,0.846154,0.55,0.666667,"depth_std, depth_range"
1,Exp_2_Depth_Gradient,4,0.52,0.50,0.4,0.450,0.53,0.833333,0.50,0.625000,"depth_std, depth_range, gradient_mean, gradien..."
2,Exp_3_Curvature_Only,2,0.76,0.15,0.6,0.375,0.29,0.850000,0.85,0.850000,"gaussian_curvature_mean, gaussian_curvature_std"
3,Exp_4_Depth_Curvature,4,0.56,0.45,0.4,0.425,0.64,0.846154,0.55,0.666667,"depth_std, depth_range, gaussian_curvature_mea..."
4,Exp_5_Full_Baseline,6,0.56,0.45,0.4,0.425,0.61,0.846154,0.55,0.666667,"depth_std, depth_range, gradient_mean, gradien..."

✅ Loaded and displayed actual 5 ablation results from: /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/ablation_results/results.csv

## SECTION 13 — SECONDARY SUBJECT-DISJOINT ROBUSTNESS EXPERIMENT (Seed 100)
Perform an independent secondary subject-disjoint split using `random_state=100`. Print train/test subjects, sample counts, class distributions, verify ZERO subject overlap, and compute all PAD metrics and confusion matrix.

In [17]:
feats_df2 = create_subject_disjoint_split(feats_df.copy(), subject_col="subject_id", label_col="label", test_ratio=0.25, random_state=100)
train_subset2 = feats_df2[feats_df2["split"] == "train"]
test_subset2 = feats_df2[feats_df2["split"] == "test"]

verify_subject_disjoint(train_subset2, test_subset2, subject_col="subject_id")

split_summary2 = summarize_split(feats_df2, subject_col="subject_id", label_col="label")
print("==========================================")
print("SECONDARY ROBUSTNESS SPLIT (SEED 100)")
print("==========================================")
print(f"Train Samples  : {split_summary2['n_train_samples']} (Subjects: {split_summary2['n_train_subjects']})")
print(f"Test Samples   : {split_summary2['n_test_samples']} (Subjects: {split_summary2['n_test_subjects']})")
print(f"Train Subjects : {sorted(list(train_subset2['subject_id'].unique()))}")
print(f"Test Subjects  : {sorted(list(test_subset2['subject_id'].unique()))}")
print(f"Train Classes  : {split_summary2['train_class_dist']}")
print(f"Test Classes   : {split_summary2['test_class_dist']}")

overlap2 = set(train_subset2["subject_id"]).intersection(set(test_subset2["subject_id"]))
print(f"Subject Overlap: {overlap2} (Count: {len(overlap2)} - ZERO LEAKAGE VERIFIED)")

X_train_full2 = train_subset2[features_to_check].values
y_train_full2 = train_subset2["label"].values
X_test_full2 = test_subset2[features_to_check].values
y_test_full2 = test_subset2["label"].values

svm_model2 = train_svm(X_train_full2, y_train_full2, C=1.0, kernel="rbf", class_weight="balanced", random_state=42)
y_pred_baseline2 = svm_model2.predict(X_test_full2)
y_prob_baseline2 = svm_model2.predict_proba(X_test_full2)[:, 1]

base_metrics2 = compute_pad_metrics(y_test_full2, y_pred_baseline2, y_prob_baseline2)
print("\n==========================================")
print("ROBUSTNESS SPLIT (SEED 100) METRICS")
print("==========================================")
print(f"Accuracy   : {base_metrics2['accuracy']:.4f}")
print(f"APCER      : {base_metrics2['apcer']:.4f}")
print(f"BPCER      : {base_metrics2['bpcer']:.4f}")
print(f"ACER       : {base_metrics2['acer']:.4f}")
print(f"ROC-AUC    : {base_metrics2['roc_auc']:.4f}")
print(f"F1-Score   : {base_metrics2['f1']:.4f}")
print(f"Confusion  : TN={base_metrics2['tn']}, FP={base_metrics2['fp']}, FN={base_metrics2['fn']}, TP={base_metrics2['tp']}")
print("\n✅ Secondary subject-disjoint robustness experiment completed cleanly.")

==========================================
SECONDARY ROBUSTNESS SPLIT (SEED 100)
==========================================
Train Samples  : 75 (Subjects: 15)
Test Samples   : 25 (Subjects: 5)
Train Subjects : [np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(48), np.int64(50), np.int64(51), np.int64(52)]
Test Subjects  : [np.int64(47), np.int64(49), np.int64(53), np.int64(54), np.int64(55)]
Train Classes  : {1: 60, 0: 15}
Test Classes   : {1: 20, 0: 5}
Subject Overlap: set() (Count: 0 - ZERO LEAKAGE VERIFIED)

==========================================
ROBUSTNESS SPLIT (SEED 100) METRICS
==========================================
Accuracy   : 0.5600
APCER      : 0.4500
BPCER      : 0.4000
ACER       : 0.4250
ROC-AUC    : 0.5700
F1-Score   : 0.6667
Confusion  : TN=3, FP=2, FN=9, TP=11

✅ Secondary subject-disjoint robustness experiment completed cleanly.

## SECTION 14 — DEEPER FAILURE ANALYSIS
Inspect false positives, false negatives, subject IDs, attack IDs, and error distributions across splits.

In [18]:
failures1 = analyze_failures(
    test_subset1, y_pred_baseline1, y_prob_baseline1,
    subject_col="subject_id",
    attack_col="attack_id" if "attack_id" in test_subset1.columns else None,
    device_col="device_id" if "device_id" in test_subset1.columns else None
)

print("==========================================")
print("PRIMARY SPLIT (SEED 42) FAILURE ANALYSIS")
print("==========================================")
print(f"Total Test Samples      : {failures1['n_test_total']}")
print(f"False Positives (Bona Fide -> Spoof) : {failures1['n_false_positives']}")
print(f"False Negatives (Spoof -> Bona Fide) : {failures1['n_false_negatives']}")
print(f"FP Subject IDs          : {failures1['false_positive_subjects']}")
print(f"FN Subject IDs          : {failures1['false_negative_subjects']}")

if "per_attack_breakdown" in failures1:
    import json
    print("\nPer-Attack Error Breakdown:")
    print(json.dumps(failures1["per_attack_breakdown"], indent=2))

==========================================
PRIMARY SPLIT (SEED 42) FAILURE ANALYSIS
==========================================
Total Test Samples      : 25
False Positives (Bona Fide -> Spoof) : 1
False Negatives (Spoof -> Bona Fide) : 6
FP Subject IDs          : [np.int64(51)]
FN Subject IDs          : [np.int64(44), np.int64(53)]

Per-Attack Error Breakdown:
{
  "2": {
    "total_samples": 5,
    "missed_attacks": 2,
    "apcer": 0.4
  },
  "3": {
    "total_samples": 5,
    "missed_attacks": 2,
    "apcer": 0.4
  },
  "4": {
    "total_samples": 5,
    "missed_attacks": 2,
    "apcer": 0.4
  },
  "5": {
    "total_samples": 5,
    "missed_attacks": 0,
    "apcer": 0.0
  }
}

In [29]:
from pathlib import Path

repo_dir = Path("/content/3DFaceReconstruction-With-Occlusion")

files = {
    "analysis": repo_dir / "scripts" / "generate_final_analysis.py",
    "ablation": (
        repo_dir / "src/face_recon_occlusion/"
        "evaluation/ablation.py"
    ),
    "metrics": (
        repo_dir / "src/face_recon_occlusion/"
        "evaluation/pad_metrics.py"
    ),
}

contents = {name: path.read_text() for name, path in files.items()}


def replace_once(text, old, new, description):
    count = text.count(old)

    if count == 0:
        if new in text:
            print("Already patched:", description)
            return text
        raise RuntimeError(
            f"Could not find expected code for: {description}"
        )

    if count != 1:
        raise RuntimeError(
            f"Expected one match for {description}, found {count}"
        )

    print("Patching:", description)
    return text.replace(old, new, 1)


# --------------------------------------------------
# 1. Fix primary and robustness ROC-AUC calculations
# --------------------------------------------------
p = contents["analysis"]

p = replace_once(
    p,
    '''    y_prob_prim = svm_primary.predict_proba(test_primary[features_list].values)[:, 1]
    m_primary = compute_pad_metrics(test_primary["label"].values, y_pred_prim, y_prob_prim)''',
    '''    y_score_prim = svm_primary.decision_function(test_primary[features_list].values)
    y_prob_prim = svm_primary.predict_proba(test_primary[features_list].values)[:, 1]
    m_primary = compute_pad_metrics(test_primary["label"].values, y_pred_prim, y_score_prim)''',
    "primary split ROC-AUC",
)

p = replace_once(
    p,
    '''    y_prob_rob = svm_robust.predict_proba(test_robust[features_list].values)[:, 1] if hasattr(svm_robust, "predict_proba") else None
    m_robust = compute_pad_metrics(test_robust["label"].values, y_pred_rob, y_prob_rob)''',
    '''    y_score_rob = svm_robust.decision_function(test_robust[features_list].values)
    m_robust = compute_pad_metrics(test_robust["label"].values, y_pred_rob, y_score_rob)''',
    "robustness split ROC-AUC",
)

# Use decision scores to draw the ROC curves.
p = replace_once(
    p,
    'def generate_roc_curves(y_true1, y_prob1, y_true2, y_prob2, save_path):',
    'def generate_roc_curves(y_true1, y_score1, y_true2, y_score2, save_path):',
    "ROC function arguments",
)

p = replace_once(
    p,
    "roc_curve(y_true1, y_prob1)",
    "roc_curve(y_true1, y_score1)",
    "primary ROC curve",
)

p = replace_once(
    p,
    "if y_prob2 is not None and len(np.unique(y_true2)) > 1:",
    "if y_score2 is not None and len(np.unique(y_true2)) > 1:",
    "robustness ROC curve condition",
)

p = replace_once(
    p,
    "roc_curve(y_true2, y_prob2)",
    "roc_curve(y_true2, y_score2)",
    "robustness ROC curve",
)

p = replace_once(
    p,
    'generate_roc_curves(test_primary["label"].values, y_prob_prim, test_robust["label"].values, y_prob_rob, figures_dir / "08_roc_curve.png")',
    'generate_roc_curves(test_primary["label"].values, y_score_prim, test_robust["label"].values, y_score_rob, figures_dir / "08_roc_curve.png")',
    "ROC figure inputs",
)

contents["analysis"] = p

# --------------------------------------------------
# 2. Fix ROC-AUC in all five ablation experiments
# --------------------------------------------------
p = contents["ablation"]

p = replace_once(
    p,
    '        y_prob = pipeline.predict_proba(X_test)[:, 1] if hasattr(pipeline, "predict_proba") else None',
    '        y_score = pipeline.decision_function(X_test) if hasattr(pipeline, "decision_function") else None',
    "ablation decision scores",
)

p = replace_once(
    p,
    "        metrics = compute_pad_metrics(y_test, y_pred, y_prob)",
    "        metrics = compute_pad_metrics(y_test, y_pred, y_score)",
    "ablation ROC-AUC calculation",
)

contents["ablation"] = p

# --------------------------------------------------
# 3. Clarify the metrics argument documentation
# --------------------------------------------------
p = contents["metrics"]

p = replace_once(
    p,
    "        y_prob (np.ndarray, optional): Predicted probabilities for spoof class (1).",
    "        y_prob (np.ndarray, optional): Continuous spoof-class ranking scores; SVM decision scores are suitable for ROC-AUC.",
    "ROC-AUC argument documentation",
)

contents["metrics"] = p

# Write only after all expected code changes have been checked.
for name, path in files.items():
    path.write_text(contents[name])

print("\nPatch applied successfully.")
print("Next, rerun Section 15 to regenerate the reports.")

Patching: primary split ROC-AUC
Patching: robustness split ROC-AUC
Patching: ROC function arguments
Patching: primary ROC curve
Patching: robustness ROC curve condition
Patching: robustness ROC curve
Patching: ROC figure inputs
Patching: ablation decision scores
Patching: ablation ROC-AUC calculation
Patching: ROC-AUC argument documentation

Patch applied successfully.
Next, rerun Section 15 to regenerate the reports.

## SECTION 15 — FINAL REPORT FIGURES GENERATION & DISPLAY
Generate publication-ready figures using `scripts/generate_final_analysis.py` and display them inline.

In [30]:
from pathlib import Path
import subprocess
import sys

# Define paths
repo_dir = Path("/content/3DFaceReconstruction-With-Occlusion")
analysis_script = repo_dir / "scripts" / "generate_final_analysis.py"

output_feature_csv = Path(
    "/content/drive/MyDrive/BTP_Part2_OULU/"
    "subject_disjoint_pilot_100/oulu_geometry_features.csv"
)

output_dir = repo_dir / "outputs" / "final_analysis"

# Patch NumPy value serialization in the JSON-saving line
script_text = analysis_script.read_text()

old_line = "json.dump(summary_json, f, indent=2)"

new_line = (
    "json.dump(summary_json, f, indent=2, "
    "default=lambda obj: obj.tolist() if hasattr(obj, 'tolist') "
    "else obj.item() if hasattr(obj, 'item') else str(obj))"
)

if old_line in script_text:
    script_text = script_text.replace(old_line, new_line, 1)
    analysis_script.write_text(script_text)
    print("Fixed JSON serialization in generate_final_analysis.py")

elif "default=lambda obj" in script_text:
    print("JSON serialization fix already exists")

else:
    raise RuntimeError(
        "Could not locate the expected JSON-saving line. "
        "Please share the code around line 375."
    )

# Run the final analysis again
result = subprocess.run(
    [
        sys.executable,
        str(analysis_script),
        "--features-csv", str(output_feature_csv),
        "--output-dir", str(output_dir),
        "--seed-primary", "42",
        "--seed-robustness", "100",
    ],
    cwd=str(repo_dir),
    capture_output=True,
    text=True,
)

print("\nEXIT CODE:", result.returncode)
print("\nSTDOUT:\n", result.stdout)
print("\nSTDERR:\n", result.stderr)

if result.returncode == 0:
    print("\nSUCCESS: Final analysis completed!")
    print("Results saved to:", output_dir)
else:
    print("\nAnalysis still failed. Share the new error output.")

JSON serialization fix already exists

EXIT CODE: 0

STDOUT:
 ==========================================
BTP PART 2 FINAL ANALYSIS & REPORT BUILDER
==========================================
Input CSV    : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/oulu_geometry_features.csv
Output Dir   : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis
Figures Dir  : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures
==========================================

📊 Executing Primary Split (Seed 42) & 5 Ablation Experiments...

🔄 Executing Robustness Check (Secondary Split, Seed 100)...

🔍 Performing Granular Failure Analysis...

🎨 Generating 9 Publication-Ready Figures...
✅ Saved figures to /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures
✅ Saved summary JSON: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_experiment_summary.json
✅ Saved final results CSV: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_results.csv


STDERR:
 /content/3DFaceReconstruction-With-Occlusion/scripts/generate_final_analysis.py:235: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(data=df_test_copy, x="Status", y="depth_std", palette="Set2", ax=axes[1])


SUCCESS: Final analysis completed!
Results saved to: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis

In [31]:
from pathlib import Path
import subprocess
import sys

# --------------------------------------------------
# 1. Define paths
# --------------------------------------------------
repo_dir = Path("/content/3DFaceReconstruction-With-Occlusion")

output_feature_csv = Path(
    "/content/drive/MyDrive/BTP_Part2_OULU/"
    "subject_disjoint_pilot_100/oulu_geometry_features.csv"
)

analysis_script = repo_dir / "scripts" / "generate_final_analysis.py"

output_dir = repo_dir / "outputs" / "final_analysis"

# --------------------------------------------------
# 2. Check whether required files exist
# --------------------------------------------------
print("=" * 60)
print("SECTION 15: FINAL ANALYSIS")
print("=" * 60)

print("Repository:", repo_dir)
print("Repository exists:", repo_dir.is_dir())

print("\nAnalysis script:", analysis_script)
print("Analysis script exists:", analysis_script.is_file())

print("\nFeature CSV:", output_feature_csv)
print("Feature CSV exists:", output_feature_csv.is_file())

print("\nOutput directory:", output_dir)

if not repo_dir.is_dir():
    raise FileNotFoundError(
        f"Repository directory not found: {repo_dir}"
    )

if not analysis_script.is_file():
    raise FileNotFoundError(
        f"Analysis script not found: {analysis_script}"
    )

if not output_feature_csv.is_file():
    raise FileNotFoundError(
        "The geometry feature CSV is missing.\n"
        f"Expected file: {output_feature_csv}\n"
        "Check that Google Drive is mounted and that the "
        "earlier geometry extraction cell generated this file."
    )

# --------------------------------------------------
# 3. Run final analysis and capture the real error
# --------------------------------------------------
command = [
    sys.executable,
    str(analysis_script),
    "--features-csv",
    str(output_feature_csv),
    "--output-dir",
    str(output_dir),
    "--seed-primary",
    "42",
    "--seed-robustness",
    "100",
]

print("\nRunning command:")
print(" ".join(command))
print("-" * 60)

result = subprocess.run(
    command,
    cwd=str(repo_dir),
    capture_output=True,
    text=True,
    check=False,
)

# --------------------------------------------------
# 4. Display complete results
# --------------------------------------------------
print("\nEXIT CODE:", result.returncode)

print("\n" + "=" * 60)
print("STANDARD OUTPUT")
print("=" * 60)
print(result.stdout if result.stdout else "(No standard output)")

print("\n" + "=" * 60)
print("ERROR OUTPUT")
print("=" * 60)
print(result.stderr if result.stderr else "(No error output)")

# --------------------------------------------------
# 5. Report status
# --------------------------------------------------
if result.returncode == 0:
    print("\nSUCCESS: Final analysis completed.")
    print("Results directory:", output_dir)
else:
    print("\nFAILED: Final analysis did not complete.")
    print("Use the error output above to identify the cause.")

============================================================
SECTION 15: FINAL ANALYSIS
============================================================
Repository: /content/3DFaceReconstruction-With-Occlusion
Repository exists: True

Analysis script: /content/3DFaceReconstruction-With-Occlusion/scripts/generate_final_analysis.py
Analysis script exists: True

Feature CSV: /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/oulu_geometry_features.csv
Feature CSV exists: True

Output directory: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis

Running command:
/usr/bin/python3 /content/3DFaceReconstruction-With-Occlusion/scripts/generate_final_analysis.py --features-csv /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/oulu_geometry_features.csv --output-dir /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis --seed-primary 42 --seed-robustness 100
------------------------------------------------------------

EXIT CODE: 0

============================================================
STANDARD OUTPUT
============================================================
==========================================
BTP PART 2 FINAL ANALYSIS & REPORT BUILDER
==========================================
Input CSV    : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/oulu_geometry_features.csv
Output Dir   : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis
Figures Dir  : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures
==========================================

📊 Executing Primary Split (Seed 42) & 5 Ablation Experiments...

🔄 Executing Robustness Check (Secondary Split, Seed 100)...

🔍 Performing Granular Failure Analysis...

🎨 Generating 9 Publication-Ready Figures...
✅ Saved figures to /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures
✅ Saved summary JSON: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_experiment_summary.json
✅ Saved final results CSV: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_results.csv


============================================================
ERROR OUTPUT
============================================================
/content/3DFaceReconstruction-With-Occlusion/scripts/generate_final_analysis.py:235: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(data=df_test_copy, x="Status", y="depth_std", palette="Set2", ax=axes[1])


SUCCESS: Final analysis completed.
Results directory: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis

In [32]:
from pathlib import Path
import json
import pandas as pd

output_dir = Path(
    "/content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis"
)

# 1. List generated files
print("=== GENERATED FILES ===")

for path in sorted(output_dir.rglob("*")):
    if path.is_file():
        print(f"{path.relative_to(output_dir)} ({path.stat().st_size:,} bytes)")

# 2. Read the experiment summary
summary_path = output_dir / "final_experiment_summary.json"

print("\n=== EXPERIMENT SUMMARY ===")

if summary_path.exists():
    with summary_path.open("r") as f:
        summary = json.load(f)

    print(json.dumps(summary, indent=2)[:12000])
else:
    print("Summary JSON is missing.")

# 3. Inspect the results CSV
results_path = output_dir / "final_results.csv"

print("\n=== FINAL RESULTS CSV ===")

if results_path.exists():
    results = pd.read_csv(results_path)
    print("Shape:", results.shape)
    print("Columns:", results.columns.tolist())
    print(results.head(15).to_string(index=False))
else:
    print("Results CSV is missing.")

=== GENERATED FILES ===
final_experiment_summary.json (4,320 bytes)
final_figures/01_pipeline_diagram.png (130,024 bytes)
final_figures/06_ablation_comparison.png (148,323 bytes)
final_figures/07_confusion_matrix.png (117,436 bytes)
final_figures/08_roc_curve.png (154,873 bytes)
final_figures/09_failure_analysis.png (157,865 bytes)
final_results.csv (820 bytes)

=== EXPERIMENT SUMMARY ===
{
  "timestamp": "2026-10-15T17:16:17.495638",
  "dataset": "OULU-NPU (Pilot-100)",
  "total_samples": 100,
  "total_subjects": 20,
  "primary_split": {
    "n_total": 100,
    "n_train_samples": 75,
    "n_test_samples": 25,
    "n_train_subjects": 15,
    "n_test_subjects": 5,
    "train_class_dist": {
      "1": 60,
      "0": 15
    },
    "test_class_dist": {
      "1": 20,
      "0": 5
    }
  },
  "robustness_split": {
    "n_total": 100,
    "n_train_samples": 75,
    "n_test_samples": 25,
    "n_train_subjects": 15,
    "n_test_subjects": 5,
    "train_class_dist": {
      "1": 60,
      "0": 15
    },
    "test_class_dist": {
      "1": 20,
      "0": 5
    }
  },
  "baseline_metrics_primary": {
    "accuracy": 0.72,
    "precision": 0.9333333333333333,
    "recall": 0.7,
    "f1": 0.8,
    "roc_auc": 0.7,
    "apcer": 0.3,
    "bpcer": 0.2,
    "acer": 0.25,
    "tn": 4,
    "fp": 1,
    "fn": 6,
    "tp": 14,
    "confusion_matrix": [
      [
        4,
        1
      ],
      [
        6,
        14
      ]
    ]
  },
  "baseline_metrics_robustness": {
    "accuracy": 0.56,
    "precision": 0.8461538461538461,
    "recall": 0.55,
    "f1": 0.6666666666666666,
    "roc_auc": 0.57,
    "apcer": 0.45,
    "bpcer": 0.4,
    "acer": 0.42500000000000004,
    "tn": 3,
    "fp": 2,
    "fn": 9,
    "tp": 11,
    "confusion_matrix": [
      [
        3,
        2
      ],
      [
        9,
        11
      ]
    ]
  },
  "ablation_experiments": [
    {
      "experiment": "Exp_1_Depth_Only",
      "num_features": 2,
      "accuracy": 0.68,
      "apcer": 0.3,
      "bpcer": 0.4,
      "acer": 0.35,
      "roc_auc": 0.66,
      "precision": 0.875,
      "recall": 0.7,
      "f1": 0.7777777777777778,
      "tn": 3,
      "fp": 2,
      "fn": 6,
      "tp": 14,
      "feature_list": "depth_std, depth_range"
    },
    {
      "experiment": "Exp_2_Depth_Gradient",
      "num_features": 4,
      "accuracy": 0.72,
      "apcer": 0.3,
      "bpcer": 0.2,
      "acer": 0.25,
      "roc_auc": 0.61,
      "precision": 0.9333333333333333,
      "recall": 0.7,
      "f1": 0.8,
      "tn": 4,
      "fp": 1,
      "fn": 6,
      "tp": 14,
      "feature_list": "depth_std, depth_range, gradient_mean, gradient_std"
    },
    {
      "experiment": "Exp_3_Curvature_Only",
      "num_features": 2,
      "accuracy": 0.72,
      "apcer": 0.3,
      "bpcer": 0.2,
      "acer": 0.25,
      "roc_auc": 0.7,
      "precision": 0.9333333333333333,
      "recall": 0.7,
      "f1": 0.8,
      "tn": 4,
      "fp": 1,
      "fn": 6,
      "tp": 14,
      "feature_list": "gaussian_curvature_mean, gaussian_curvature_std"
    },
    {
      "experiment": "Exp_4_Depth_Curvature",
      "num_features": 4,
      "accuracy": 0.76,
      "apcer": 0.25,
      "bpcer": 0.2,
      "acer": 0.225,
      "roc_auc": 0.7,
      "precision": 0.9375,
      "recall": 0.75,
      "f1": 0.8333333333333334,
      "tn": 4,
      "fp": 1,
      "fn": 5,
      "tp": 15,
      "feature_list": "depth_std, depth_range, gaussian_curvature_mean, gaussian_curvature_std"
    },
    {
      "experiment": "Exp_5_Full_Baseline",
      "num_features": 6,
      "accuracy": 0.72,
      "apcer": 0.3,
      "bpcer": 0.2,
      "acer": 0.25,
      "roc_auc": 0.7,
      "precision": 0.9333333333333333,
      "recall": 0.7,
      "f1": 0.8,
      "tn": 4,
      "fp": 1,
      "fn": 6,
      "tp": 14,
      "feature_list": "depth_std, depth_range, gradient_mean, gradient_std, gaussian_curvature_mean, gaussian_curvature_std"
    }
  ],
  "failure_analysis": {
    "n_test_total": 25,
    "n_false_positives": 1,
    "n_false_negatives": 6,
    "false_positive_subjects": [
      51
    ],
    "false_negative_subjects": [
      44,
      53
    ],
    "per_attack_breakdown": {
      "2": {
        "total_samples": 5,
        "missed_attacks": 2,
        "apcer": 0.4
      },
      "3": {
        "total_samples": 5,
        "missed_attacks": 2,
        "apcer": 0.4
      },
      "4": {
        "total_samples": 5,
        "missed_attacks": 2,
        "apcer": 0.4
      },
      "5": {
        "total_samples": 5,
        "missed_attacks": 0,
        "apcer": 0.0
      }
    },
    "per_device_breakdown": {
      "1": {
        "total_samples": 25,
        "errors": 7,
        "error_rate": 0.28
      }
    }
  }
}

=== FINAL RESULTS CSV ===
Shape: (5, 15)
Columns: ['experiment', 'num_features', 'accuracy', 'apcer', 'bpcer', 'acer', 'roc_auc', 'precision', 'recall', 'f1', 'tn', 'fp', 'fn', 'tp', 'feature_list']
           experiment  num_features  accuracy  apcer  bpcer  acer  roc_auc  precision  recall       f1  tn  fp  fn  tp                                                                                         feature_list
     Exp_1_Depth_Only             2      0.68   0.30    0.4 0.350     0.66   0.875000    0.70 0.777778   3   2   6  14                                                                               depth_std, depth_range
 Exp_2_Depth_Gradient             4      0.72   0.30    0.2 0.250     0.61   0.933333    0.70 0.800000   4   1   6  14                                                  depth_std, depth_range, gradient_mean, gradient_std
 Exp_3_Curvature_Only             2      0.72   0.30    0.2 0.250     0.70   0.933333    0.70 0.800000   4   1   6  14                                                      gaussian_curvature_mean, gaussian_curvature_std
Exp_4_Depth_Curvature             4      0.76   0.25    0.2 0.225     0.70   0.937500    0.75 0.833333   4   1   5  15                              depth_std, depth_range, gaussian_curvature_mean, gaussian_curvature_std
  Exp_5_Full_Baseline             6      0.72   0.30    0.2 0.250     0.70   0.933333    0.70 0.800000   4   1   6  14 depth_std, depth_range, gradient_mean, gradient_std, gaussian_curvature_mean, gaussian_curvature_std

In [33]:
from pathlib import Path

repo_dir = Path("/content/3DFaceReconstruction-With-Occlusion")
final_out_dir = repo_dir / "outputs" / "final_analysis"

print("Section 16 output directory:", final_out_dir)
print("Directory exists:", final_out_dir.exists())

Section 16 output directory: /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis
Directory exists: True

## SECTION 16 — FINAL SUMMARY FILES & REPORT EXPORT
Export and verify `final_results.csv`, `final_experiment_summary.json`, and `FINAL_ANALYSIS.md`.

In [34]:
final_csv_file = final_out_dir / "final_results.csv"
final_json_file = final_out_dir / "final_experiment_summary.json"
final_md_file = repo_dir / "FINAL_ANALYSIS.md"

print(f"Checking final_results.csv       : {final_csv_file.exists()}")
print(f"Checking final_summary.json      : {final_json_file.exists()}")
print(f"Checking FINAL_ANALYSIS.md       : {final_md_file.exists()}")

if final_csv_file.exists():
    print("\n=== FINAL RESULTS TABLE (final_results.csv) ===")
    display(pd.read_csv(final_csv_file)[["experiment", "num_features", "accuracy", "apcer", "bpcer", "acer", "roc_auc", "f1"]])

print("\n✅ Summary files export and verification complete.")

Checking final_results.csv       : True
Checking final_summary.json      : True
Checking FINAL_ANALYSIS.md       : True

=== FINAL RESULTS TABLE (final_results.csv) ===

,experiment,num_features,accuracy,apcer,bpcer,acer,roc_auc,f1
0,Exp_1_Depth_Only,2,0.68,0.30,0.4,0.350,0.66,0.777778
1,Exp_2_Depth_Gradient,4,0.72,0.30,0.2,0.250,0.61,0.800000
2,Exp_3_Curvature_Only,2,0.72,0.30,0.2,0.250,0.70,0.800000
3,Exp_4_Depth_Curvature,4,0.76,0.25,0.2,0.225,0.70,0.833333
4,Exp_5_Full_Baseline,6,0.72,0.30,0.2,0.250,0.70,0.800000

✅ Summary files export and verification complete.

## SECTION 17 — OUTPUT FILES VERIFICATION
Final verification cell confirming that all required experimental outputs, figures, and summary reports exist.

In [35]:
print("==========================================================================================")
print("FINAL EXPERIMENTAL VERIFICATION CHECKLIST")
print("==========================================================================================")
expected_files = [
    output_feature_csv,
    ablation_out_dir / "experiment_config.json",
    ablation_out_dir / "results.csv",
    final_out_dir / "final_results.csv",
    final_out_dir / "final_experiment_summary.json",
    final_out_dir / "final_figures" / "01_pipeline_diagram.png",
    final_out_dir / "final_figures" / "06_ablation_comparison.png",
    final_out_dir / "final_figures" / "07_confusion_matrix.png",
    final_out_dir / "final_figures" / "08_roc_curve.png",
    final_out_dir / "final_figures" / "09_failure_analysis.png",
    repo_dir / "FINAL_ANALYSIS.md",
]

all_passed = True
for ef in expected_files:
    status = "✅ EXISTS" if ef.exists() else "❌ MISSING"
    if not ef.exists(): all_passed = False
    print(f"  {status} : {ef}")

print("==========================================================================================")
if all_passed:
    print("🎉 ALL EXPECTED EXPERIMENTAL OUTPUT FILES VERIFIED SUCCESSFULLY.")
else:
    print("⚠️ WARNING: Some expected output files were not found.")

==========================================================================================
FINAL EXPERIMENTAL VERIFICATION CHECKLIST
==========================================================================================
  ✅ EXISTS : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/oulu_geometry_features.csv
  ✅ EXISTS : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/ablation_results/experiment_config.json
  ✅ EXISTS : /content/drive/MyDrive/BTP_Part2_OULU/subject_disjoint_pilot_100/ablation_results/results.csv
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_results.csv
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_experiment_summary.json
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures/01_pipeline_diagram.png
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures/06_ablation_comparison.png
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures/07_confusion_matrix.png
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures/08_roc_curve.png
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/outputs/final_analysis/final_figures/09_failure_analysis.png
  ✅ EXISTS : /content/3DFaceReconstruction-With-Occlusion/FINAL_ANALYSIS.md
==========================================================================================
🎉 ALL EXPECTED EXPERIMENTAL OUTPUT FILES VERIFIED SUCCESSFULLY.

In [36]:
import pandas as pd
from sklearn.metrics import roc_auc_score
from face_recon_occlusion.data import create_subject_disjoint_split
from face_recon_occlusion.models import train_svm

csv_path = (
    "/content/drive/MyDrive/BTP_Part2_OULU/"
    "subject_disjoint_pilot_100/oulu_geometry_features.csv"
)

df = pd.read_csv(csv_path)

features = [
    "depth_std",
    "depth_range",
    "gradient_mean",
    "gradient_std",
    "gaussian_curvature_mean",
    "gaussian_curvature_std",
]

# Reproduce the primary subject-disjoint split
split_df = create_subject_disjoint_split(
    df,
    subject_col="subject_id",
    label_col="label",
    test_ratio=0.25,
    random_state=42,
)

train_df = split_df[split_df["split"] == "train"]
test_df = split_df[split_df["split"] == "test"]

model = train_svm(
    train_df[features].values,
    train_df["label"].values,
    random_state=42,
)

y_true = test_df["label"].astype(int).values
probabilities = model.predict_proba(test_df[features].values)

classes = list(model.named_steps["svm"].classes_)
spoof_index = classes.index(1)
spoof_prob = probabilities[:, spoof_index]

decision_scores = model.decision_function(
    test_df[features].values
)

print("Model classes:", classes)
print("Test samples:", len(test_df))
print("Train/test subjects disjoint:",
      set(train_df["subject_id"]).isdisjoint(
          set(test_df["subject_id"])
      ))

print("ROC-AUC using spoof probabilities:",
      round(roc_auc_score(y_true, spoof_prob), 4))

print("ROC-AUC using SVM decision scores:",
      round(roc_auc_score(y_true, decision_scores), 4))

print("ROC-AUC using inverted probabilities:",
      round(roc_auc_score(y_true, 1 - spoof_prob), 4))

Model classes: [np.int64(0), np.int64(1)]
Test samples: 25
Train/test subjects disjoint: True
ROC-AUC using spoof probabilities: 0.3
ROC-AUC using SVM decision scores: 0.7
ROC-AUC using inverted probabilities: 0.7

In [37]:
from pathlib import Path
import re

repo_dir = Path("/content/3DFaceReconstruction-With-Occlusion")
report_path = repo_dir / "FINAL_ANALYSIS.md"

print("Report exists:", report_path.exists())

if report_path.exists():
    lines = report_path.read_text().splitlines()

    for number, line in enumerate(lines, start=1):
        if re.search(
            r"roc.?auc|accuracy|baseline|ablation|robustness|"
            r"0\.30|0\.70|0\.57",
            line,
            re.IGNORECASE,
        ):
            print(f"{number}: {line}")

Report exists: True
59: Six baseline scalar geometric features were extracted directly from the reconstructed 3D OBJ meshes:
72: The baseline classifier is configured as:
80: ## 6. Baseline Results
86: | **Accuracy** | `0.5600` |
90: | **ROC-AUC** | **`0.6100`** |
100: ## 7. Ablation Results
102: Five feature ablation experiments were executed on the subject-disjoint split:
104: | Experiment | Feature Group | # Features | Accuracy | APCER | BPCER | ACER | ROC-AUC | F1-Score |
110: | **Exp 5** | Full Baseline (All 6 Features) | 6 | **0.5600** | **0.4500** | **0.4000** | **0.4250** | **0.6100** | **0.6667** |
112: ### Ablation Findings:
113: - **Depth Only (Exp 1)** yielded an ACER of `0.4500` and ROC-AUC of `0.5800`.
114: - **Adding Depth Gradient (Exp 2)** improved ACER to `0.4250` and ROC-AUC to `0.6000`.
115: - **Curvature Only (Exp 3)** independently achieved ACER `0.4250` and ROC-AUC `0.5900`, demonstrating that curvature retains standalone discriminative signal.
116: - **Combining All 6 Features (Exp 5)** achieved the highest overall ROC-AUC (`0.6100`), confirming complementary interaction between depth variance, depth gradient magnitude, and Gaussian curvature measure.
120: ## 8. Robustness Evaluation
124: | Metric | Primary Split (Seed 42) | Secondary Robustness Split (Seed 100) |
128: | **Accuracy** | `0.5600` | `0.6000` |
132: | **ROC-AUC** | `0.6100` | `0.6300` |
134: ### Robustness Findings:
150:    - Attack Type 5 (Video Replay / Curtains): APCER = `0.20` (Highest detection accuracy).
160: 2. **Small Held-Out Test Set**: The test set comprises 25 samples across 5 subjects. Small changes in single predictions ($1 / 25$) alter overall accuracy by $4\%$.
168: - **Primary Conclusion**: The pilot experiment indicates that 3D geometric surface cues extracted from reconstructed monocular meshes provide non-random discriminative information for face presentation attack detection (Baseline ACER `0.4250`, ROC-AUC `0.6100` under subject-disjoint evaluation).